### ISSUE TITLE
/sandbox/public_token/create request fails if options provided

### ISSUE THREAD

**Issue by vladislavkoz** [plaid/plaid-postman#142] opened 2023-03-08 09:30 UTC
Tested with both: Postman collection and plaid-python==11.6.0
[1] Postman collection
Postman request:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/40685761/223674009-a19f08d2-6224-4d49-afa9-fa10cb6b9ec2.png">

Postman error(it works fine without "options" field):
<img width="663" alt="image" src="https://user-images.githubusercontent.com/40685761/223672994-104e6dc6-8405-40b5-b591-fb7f86e31870.png">

[2] plaid-python
plaid-python code:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/40685761/223673746-c72b7c0c-6058-443a-9755-eccb0bcf5657.png">

plaid-python error(it works fine without "options" parameter):
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/40685761/223673521-41394368-49ea-4d45-a06f-605f92d6952b.png">

[3] I was able to create a custom api user with dashboard(https://dashboard.plaid.com/team/sandbox).
Can you clarify whether it's possible to use the custom sandbox user for all the sandbox institutions? Currently I have a user but I can't use it. It works fine if I use user_good, pass_good credentials but it fails if I try [custom_user_1, <ANY_NOT_EMPTY_PASSWORD>]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/40685761/223675511-871781ba-0acc-4f3a-b51c-511e17ef1cc5.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/40685761/223675403-1bbb16cb-7254-4b6b-8c32-f2d258d4606d.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/40685761/223675218-7424001e-4a82-42dd-b6ba-13b477941778.png">

**Comment by phoenixy1** [comment] 2023-03-08 17:28
Hmmm...possibly this should be clearer in the docs, but I think the issue is that if you are providing an `override_username` you must also provide an `override_password`. Try that and I think it should fix your problem.

**Comment by vladislavkoz** [comment] 2023-03-08 19:57
> Hmmm...possibly this should be clearer in the docs, but I think the issue is that if you are providing an `override_username` you must also provide an `override_password`. Try that and I think it should fix your problem.

No success. I've tried different scenarios.
<img width="994" alt="Screenshot 2023-03-08 at 21 49 57" src="https://user-images.githubusercontent.com/40685761/223831244-aa1ae522-2112-42a2-adb2-bc3f79c17b27.png">

Default one:
<img width="994" alt="Screenshot 2023-03-08 at 21 50 24" src="https://user-images.githubusercontent.com/40685761/223831356-45ceb973-5ad8-4814-b02a-54610d2c0a84.png">
 
With the user config from [this repo](https://github.com/plaid/sandbox-custom-users/) as a value
<img width="994" alt="Screenshot 2023-03-08 at 21 52 00" src="https://user-images.githubusercontent.com/40685761/223831753-777da44e-5154-4d2b-913b-dedee33bc334.png">

I've tried all the options above with both the Postman collection and plaid-python.

Probably I need some specific value for the password field.

**Comment by vladislavkoz** [comment] 2023-03-08 19:58
It returns a 500 status code. It doesn't look like it's some validation error.

**Comment by phoenixy1** [comment] 2023-03-08 20:35
@vladislavkoz I need to look a little bit more into how/whether it's possible to send a configuration object via the password in `/sandbox/public_token/create` that way, but I was able to create a custom user via the Dashboard at https://dashboard.plaid.com/team/sandbox and then successfully use that user with `/sandbox/public_token/create` (enter any non-empty string as the password) -- does that flow work for you?

**Comment by vladislavkoz** [comment] 2023-03-10 09:11
Is there any limit on the number of transactions for the custom sandbox? I got it works(custom user created via Dashboard) when I reduced the transactions list.

**Comment by phoenixy1** [comment] 2023-03-10 19:06
Hmm, I'm not aware of a limit -- is it possible that maybe one or more of your custom transactions that you're removing could be malformatted, and so removing it causes the object to work? If you could share the configuration object, that might help us troubleshoot and figure out what's going on.

**Comment by phoenixy1** [comment] 2023-03-11 00:02
@vladislavkoz thank you for the report! I looked into this some more and it turns out that there is a limit on the size of this file -- we consider that to be a bug, but fixing it properly to support arbitrarily large payloads would involve some substantial work, and using `user_custom` with hundreds of transactions is a pretty uncommon use case, so it hasn't been prioritized. If this is a serious impediment to your testing, let us know and we can see if there might be a creative way to work around it.

**Comment by vladislavkoz** [comment] 2023-03-11 17:59
Thank you very much. Really appreciate it. We are not blocked for now and I think it's not critical for us at this moment.

**Comment by vladislavkoz** [comment] 2023-03-11 17:59
Would you like me to close this ticket?

**Comment by phoenixy1** [comment] 2023-03-13 16:42
@vladislavkoz Sure, I'll close it up if we're good here!

**Closed by phoenixy1** 2023-03-13 16:42 UTC
